### ISSUE TITLE
Security issue due to exposed MySQL password

### ISSUE THREAD

**Issue by SaranshBangar** [Niketiiitd/DBMS_BOOKSTORE#1]
# Problem

I noticed that you have not hidden your MySQL password in your python files

![WhatsApp Image 2024-05-19 at 13 15 15_76839a2a](https://github.com/Niketiiitd/DBMS_BOOKSTORE/assets/114401238/58cd735b-14fc-41d5-89e2-3004ca507e8d)

This may lead to a potential security issue in the near future as any person with malicious intent can pass harmful malware directly into your workstation

## Solution 1

Create a `.env.local` file to store sensitive data

## Solution 2

Manually hide your password by replacing it with stars or hashes

**Comment by Niketiiitd** [comment]
Dear saransh,
Thanks for helping me in reviewing my project on github.

Regards,
Niket agarwal
